name: CabinetOpeningStructuredEE-v1

env:
  episodeLength: 50

  obs_type: pixels
  im_size: 224

  cam:
    crop: center
    w: 298
    h: 224
    fov: 120
    ss: 2
    loc_p: [0.04, 0.0, 0.045]
    loc_r: [180, -90.0, 0.0]
